BACKGROUND_COLOR: darkgray
SCREEN_RES: [1920, 1080]
FIX_CROSS_TIME_S: 1
FIX_CROSS_COLOR: black
NO_TRAINING_TRIALS: 20
TRIALS_IN_BLOCK: 100
NO_BLOCKS: 2
STIM_TIME_S: 3
REACTION_KEYS: [left, right]
TEXT_HEIGHT: 60
